import "./globals.css";
import { Inter } from "next/font/google";

// import styles from "./layout.module.css";

const inter = Inter({ subsets: ["latin"] });

import Navbar from "@components/Navbar/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Avo Project</title>
      </head>
      <body className={inter.className}>
        {/* <div className={styles.container}> */}
        <div>
          <header>
            <Navbar></Navbar>
          </header>
          {children}
          <footer className="container">Este es el footer</footer>
        </div>
        <style>{`
          .container {
            background: black;
          }
        `}</style>
      </body>
    </html>
  );
}
