import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Avo Project</title>
      </head>
      <body className={inter.className}>
        <header>Este es el header</header>
        {children}
        <footer>Este es el footer</footer>
      </body>
    </html>
  );
}
